# Generated by Django 3.1.7 on 2021-02-26 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210226_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 2, 26, 18, 15, 41, 833300, tzinfo=utc), max_length=100, verbose_name='Имя автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='anime',
            name='author',
        ),
        migrations.AddField(
            model_name='anime',
            name='author',
            field=models.ManyToManyField(to='mainapp.Author', verbose_name='Автор'),
        ),
    ]
