# Generated by Django 3.1.7 on 2021-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210226_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(default=None, verbose_name='Номер серии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(choices=[('Зима', 'Зима'), ('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень')], max_length=10),
        ),
    ]
