# Generated by Django 3.1.7 on 2021-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210301_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер серии'),
        ),
    ]
