# Generated by Django 3.1.7 on 2021-03-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210301_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(default=None, verbose_name='Номер серии'),
        ),
    ]
